# Generated by Django 4.2.6 on 2023-10-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('diarydate', models.DateTimeField()),
                ('diaryweather', models.CharField(max_length=50)),
                ('diaryemoji', models.CharField(max_length=100)),
                ('diarycontent', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='diaryimages/')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('nickname', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
